### ISSUE TITLE
notification API must be called in the wrong way 

### ISSUE THREAD

**Issue by vkarakolis-epu** [QualiChain/fe#380]
API expects a user_id (integer) and it gets a string “bob”. Logs: 
 

2021-04-26 12:25:26,908 - application.notifications.routes - ERROR - (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for integer: "bob" 

LINE 1: ...Machine Learning scheduled to 01/05/2021', false, 'bob') RET... 

^ 

[SQL: INSERT INTO notifications (message, read, user_id) VALUES (%(message)s, %(read)s, %(user_id)s) RETURNING notifications.id] 

[parameters: {'message': 'Skill evaluation for skill Machine Learning scheduled to 01/05/2021', 'read': False, 'user_id': 'bob'}] 

(Background on this error at: http://sqlalche.me/e/9h9h) 

[SQL: INSERT INTO notifications (message, read, user_id) VALUES (%(message)s, %(read)s, %(user_id)s) RETURNING notifications.id] 

[parameters: {'message': 'Skill evaluation for skill Machine Learning scheduled to 01/05/2021', 'read': False, 'user_id': 'bob'}] 

(Background on this error at: http://sqlalche.me/e/9h9h) 

[2021-04-26 12:25:26 +0000] [23] [ERROR] Error handling request /notifications 

Traceback (most recent call last): 

File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle 

self.handle_request(listener, req, client, addr) 

File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request 

respiter = self.wsgi(environ, resp.start_response) 

File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__ 

return self.wsgi_app(environ, start_response) 

File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_a

**Comment by mmilaprat** [comment]
@vkarakolis-epu , are you sure that this issue is for the FE?

**Comment by mmilaprat** [comment]
The FE only gets data from this API, it doesn't sends data to the PAI. 
The first version of the FE sends dummy databut  just to test that we can recover it, but since them FE doesn't send data anymoer to the notifications API.

**Comment by mmilaprat** [comment]
can we close this issue?
